name: Compile Proto Files

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  compile-proto:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install grpcio==1.71.0 grpcio-tools==1.71.0 protobuf==5.29.4
      
      - name: Compile proto files
        run: |
          mkdir -p src/ppv/v1
          python -m grpc_tools.protoc \
            --proto_path=proto \
            --python_out=src \
            --grpc_python_out=src \
            proto/ppv/v1/ppv.proto
      
      - name: Create zip artifact
        run: |
          zip -r proto_compiled.zip src/ppv
          
      - name: Upload to release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: proto_compiled.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Upload as workflow artifact
        uses: actions/upload-artifact@v3
        with:
          name: compiled-proto
          path: proto_compiled.zip